# Build settings
permalink   : /blog/:title/
markdown    : kramdown
highlighter : rouge
gems: [jekyll-paginate, jekyll-sitemap]
repository: https://github.com/michal-franc/michal-franc.github.io

paginate: 10
paginate_path: "/blog/page/:num/"
comments: true

repository: michal-franc/michal-franc.github.io

destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Michal Franc | Cloud Native, Devops, Architecture
description: "Software Engineer/Architect-distributed systems, cloud-native, system design, platform engineering, golang, kubernetes"
keywords: "michal franc,engineer,cloud,architecture,cloud native,platform,distributed systems,golang, kubernetes"
image:
url: http://www.mfranc.com
baseurl: ""

google_analytics: UA-15894596-3
disqus_shortname: "MichalFranc"
disqus_site_shortname: "thesilenceofthelams"

# Author settings
author:
  name      : Michal Franc
  bio1      : "Staff+ Engineer with 16+ years of experience including 12 years designing/building/supporting cloud based systems. Experienced in, and able to, wear different types of `hats` from Individual Contributor to Architecture and Leadership roles."
  bio2      : "expert in: cloud-native, platform engineering, k8s, devops/sre, architecture, and distributed systems"
  thumb     : /images/author.jpg
  email     : lam.michal.franc@gmail.com
  url       : http://www.mfranc.com
  github    : http://github.com/michal-franc
  twitter   : http://twitter.com/francmichal
  linkedin  : https://uk.linkedin.com/in/michalfranc1

# navbar pages
navbar:
  - slug: blog
    title: Posts
  - slug: blog/articles
    title: Articles
  - slug: about 
    title: About

# draft support
collections:
  drafts:
    output: true

defaults:
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: draft

kramdown:
  parse_block_html: true


exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
