# Build settings
permalink   : /blog/:title/
markdown    : kramdown
highlighter : rouge
gems: [jekyll-paginate, jekyll-sitemap]
repository: https://github.com/michal-franc/michal-franc.github.io

paginate: 10
paginate_path: "/blog/page/:num/"
comments: true

repository: michal-franc/michal-franc.github.io

destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Michal Franc | Leader, Engineer, Speaker
description: "Experienced Engineering Lead - architect, distributed systems, cloudnative, system design expert"
keywords: "michal franc,leader,programmer,coach,speaker"
image: "default_share_image.jpg"
url: http://www.mfranc.com
baseurl: ""

google_analytics: UA-15894596-3
disqus_shortname: "MichalFranc"
disqus_site_shortname: "thesilenceofthelams"

# Author settings
author:
  name      : Michal Franc
  job       : Engineer @ Just Eat
  bio       : "Experienced Engineering Lead, <3 vim, mint and i3wm, expert in: architecture, distributed systems, systems design and #cloudnative"
  thumb     : /images/author.jpg
  email     : lam.michal.franc@gmail.com
  url       : http://www.mfranc.com
  github    : http://github.com/michal-franc
  twitter   : http://twitter.com/francmichal
  facebook  : http://facebook.com/michalfrancblog
  linkedin  : https://uk.linkedin.com/in/michalfranc1

# navbar pages
navbar:
  - slug: blog
    title: Posts
  - slug: blog/articles
    title: Articles
  - slug: about 
    title: About
  - slug: hire-me
    title: Hire Me

# draft support
collections:
  drafts:
    output: true

defaults:
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: draft

kramdown:
  parse_block_html: true


exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
