# Site settings
title: Michal Franc 
email: lam.michal.franc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mfranc.com" # the base hostname & protocol for your site
twitter_username: francmichal 
github_username:  michal-franc

# Build settings
markdown: kramdown
highlighter: pygments
