# Build settings
permalink   : /blog/:title/
markdown    : kramdown
highlighter : pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Michal Franc
description: "Experienced Engineer, Lead"
keywords: "Michal Franc, Franc, Engineer, Lead"
url: http://www.mfranc.com
baseurl: ""

google_analytics: UA-15894596-3
disqus_shortname: "MichalFranc"
disqus_site_shortname: "thesilenceofthelams"

# Author settings
author:
  name      : Michal Franc
  job       : Lead Engineer 
  bio       : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb     : /images/author.jpg
  email     : lam.michal.franc@gmail.com
  url       : http://www.mfranc.com
  github    : http://github.com/michal-franc
  twitter   : http://twitter.com/francmichal
  facebook  : http://facebook.com/michal.franc.9
  linkedin  : https://uk.linkedin.com/in/michalfranc1

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: resume
    title: Resume
  - slug: speaking
    title: Speaking
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
